### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by merqlove** [chr4-cookbooks/duplicity_ng#24]
Hello Chris,

Today we have started moving to BizSpark servers, so i think to do DuplicityNg support for Azure Blob Storage containers.

1. As i see, we need https://github.com/Azure/azure-sdk-for-python dependency
2. As well as endpoint for Azure is: `azure://container_name`

Keys: 
- AZURE_ACCOUNT_NAME
- AZURE_ACCOUNT_KEY

**Comment by chr4** [comment]
I'd gladly merge a good pull-requests for Azure support!
