### ISSUE TITLE
Restore question

### ISSUE THREAD

**Issue by merqlove** [chr4-cookbooks/duplicity_ng#32]
Sometimes we use restore option, for example we need to restore some server or when we moving to another stack. 
Do you know best way to restore with minimum of `cat`, `export PASSPHRASE` and so on operations?

**Comment by chr4** [comment]
For this reason, I created the `confdir` attribute. The files placed there can be sourced and then `DUPLICITY_ARGUMENTS` can be used. 

Example for Ubuntu (This should probably go to the README, too)
```shell
source /etc/defaults/duplicity-test
duplicity collection-status ${DUPLICITY_ARGUMENTS[@]} 
```

The same works for all other duplicity commands (restore, etc). Does that help?

**Comment by merqlove** [comment]
Thanks for info.
Yeah, this is good way.
