### ISSUE TITLE
0.7.02 unavailable

### ISSUE THREAD

**Issue by merqlove** [chr4-cookbooks/duplicity_ng#35]
Tried to deploy with .02 url, and today it's not working. .03 works well.
#### Working defaults:
version: 0.7.03
checksum: dec756ebe6cd25a6a55d9f31954fd8e07f4502063e4e148bdde4b1b3b2ad4615

**Comment by chr4** [comment]
Mmh, according to https://launchpad.net/duplicity/+milestone/0.7.02 it is still available. 
Would you mind filing a pull-request for the 0.7.03 release? upgrading won't hurt :)

**Comment by merqlove** [comment]
I think it was launchpad store bug, specially for me :)
Because 1 day ago my local tests worked fine.
#36
