### ISSUE TITLE
granular cron config?

### ISSUE THREAD

**Issue by rmoriz** [chr4-cookbooks/duplicity_ng#38]
Currently backup jobs can only be scheduled using the default intervals (hourly, daily, weekly, monthly). In some cases, when e.g. a backup takes 2 hours but should be done at least 3 times a day, you're currently out of luck.

Given that you already abstract the config files into `confdir`, how about writing the relevant shell scripts somewhere in a `bindir` and make the cronjob integration optional?

A user could then use the `cron` cookbook for an "complex" cron integration, or use another scheduler (systemd… whatever)

**Comment by chr4** [comment]
I agree, that this is a good idea. As `confdir` I'm using the global configuration directories of the distribution, e.g. on Ubuntu `/etc/defaults`. I assume that placing a shellscript would rather fit into a directory like `/usr/local/lib/duplicity/$name` or something alike.

Pull requests welcome!

**Comment by merqlove** [comment]
:+1:
