### ISSUE TITLE
python cookbook dependency

### ISSUE THREAD

**Issue by rmoriz** [chr4-cookbooks/duplicity_ng#43]
the `python` cookbook is deprecated for some years and throws deprecation warnings that it will fail with chef13 (which will be released on April 10th).

https://supermarket.chef.io/cookbooks/python

Probably the way to go: migrate to https://supermarket.chef.io/cookbooks/poise-python

see https://github.com/poise/poise-python#upgrading-from-the-python-cookbook

**Comment by chr4** [comment]
Thanks for the info!

Mmh, another option would be to drop `pip` support from the cookbook. I think @merqlove added support for `pip` and the python dependency back then. Can you comment on this? Is the python support still required?

**Comment by merqlove** [comment]
Hi, seems that it can work from sources instead.

Best regards, 
Alexander Merkulov

**Comment by rmoriz** [comment]
Other issues:

- kitchen: oudated bento boxes were removed from atlas
- minitest: broken, hangs also depcrecated by chef for some years for serverspec, now deprecated for chefs own "inspec" framework
- poise-python: it seems that it cannot install pip from local .tar.gz file which breaks the GnuPGInterface package. (investigation)

**Comment by chr4** [comment]
Thank you for looking into this! As far as I'm concerned, we can drop the `pip` and `python` support completely. All servers I'm operating are recent enough to provide adequate packages.

**Comment by rmoriz** [comment]
Okay, I'll do some refactorings and aim for a new major release, are you okay with that?

**Comment by chr4** [comment]
That would be awesome! If it's something big, try splitting it up into smaller pull-requests or commit early. That makes reviewing a little easier.

Suggestions:
- [ ] Replace `rubocop` with `cookstyle`

**Comment by rmoriz** [comment]
I tried it but too much is broken. Minitest handler is already broken with chef12, many kitchen targets are not on atlas anymore, Gemfile.lock is not there, nor chefdk...



Von meinem iPhone gesendet

**Comment by gsreynolds** [comment]
Hi! Noticed this issue and just wanted to contribute the changes in #45 for moving the pip install to poise-python if you wanted to keep that in the cookbook. Converges successfully under install-source-pip-debian-87, install-source-pip-centos-73 and install-source-pip-ubuntu-1604.

**Comment by chr4** [comment]
Closing this in favor of https://github.com/chr4-cookbooks/duplicity_ng/pull/45
